// Copyright-safe factual schedule layer.
// Only event facts (date/time/institution/category) supported by official institutional
// sources are normalized here. No source prose, charts, logos or third-party calendar
// compilations are copied. Source URLs are retained for attribution and verification.

const checked = () => new Date().toISOString();
const e = (x) => ({ status: 'confirmed', lastChecked: checked(), ...x });

export function officialSeed(){
  return [
    // CHINA — National Bureau of Statistics 2026 official release calendar.
    e({country:'CN',market:'China',event:'Official Manufacturing & Non-Manufacturing PMI',category:'activity',date:'2026-09-30',time:'09:30',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE','CREDIT','EQUITIES'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Consumer Price Index (CPI)',category:'inflation',date:'2026-10-14',time:'09:30',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Producer Price Index (PPI)',category:'inflation',date:'2026-10-14',time:'09:30',timezone:'Asia/Shanghai',importance:'medium',transmissionChannels:['RATES','FX','CREDIT'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'National Economic Performance — Q3 / September activity',category:'growth',date:'2026-10-19',time:'10:00',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE','CREDIT','EQUITIES'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Official Manufacturing & Non-Manufacturing PMI',category:'activity',date:'2026-10-31',time:'09:30',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE','CREDIT','EQUITIES'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Consumer Price Index (CPI)',category:'inflation',date:'2026-11-09',time:'09:30',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Producer Price Index (PPI)',category:'inflation',date:'2026-11-09',time:'09:30',timezone:'Asia/Shanghai',importance:'medium',transmissionChannels:['RATES','FX','CREDIT'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'National Economic Performance — October activity',category:'activity',date:'2026-11-16',time:'10:00',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE','CREDIT','EQUITIES'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Official Manufacturing & Non-Manufacturing PMI',category:'activity',date:'2026-11-30',time:'09:30',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE','CREDIT','EQUITIES'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Consumer Price Index (CPI)',category:'inflation',date:'2026-12-09',time:'09:30',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Producer Price Index (PPI)',category:'inflation',date:'2026-12-09',time:'09:30',timezone:'Asia/Shanghai',importance:'medium',transmissionChannels:['RATES','FX','CREDIT'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'National Economic Performance — November activity',category:'activity',date:'2026-12-15',time:'10:00',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE','CREDIT','EQUITIES'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),
    e({country:'CN',market:'China',event:'Official Manufacturing & Non-Manufacturing PMI',category:'activity',date:'2026-12-31',time:'09:30',timezone:'Asia/Shanghai',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE','CREDIT','EQUITIES'],source:'National Bureau of Statistics of China',sourceUrl:'https://www.stats.gov.cn/english/PressRelease/ReleaseCalendar/202512/t20251226_1962154.html'}),

    // SINGAPORE — Enterprise Singapore publishes monthly trade statistics on the
    // 17th, or the nearest working day when the 17th is a weekend/public holiday.
    // These entries are explicitly marked as rule-based scheduled dates rather than
    // institution-announced one-off meeting dates.
    e({country:'SG',market:'Singapore',event:'Singapore External Trade / NODX',category:'trade',date:'2026-10-16',time:null,timezone:'Asia/Singapore',importance:'high',transmissionChannels:['FX','RATES','CREDIT','EQUITIES'],source:'Enterprise Singapore',sourceUrl:'https://www.enterprisesg.gov.sg/resources/media-centre/media-releases/2026/september/mr04226_singapore-external-trade-august-2026',notes:'Scheduled from Enterprise Singapore’s published standing release rule: monthly trade statistics are released on the 17th or nearest working day.'}),
    e({country:'SG',market:'Singapore',event:'Singapore External Trade / NODX',category:'trade',date:'2026-11-17',time:null,timezone:'Asia/Singapore',importance:'high',transmissionChannels:['FX','RATES','CREDIT','EQUITIES'],source:'Enterprise Singapore',sourceUrl:'https://www.enterprisesg.gov.sg/resources/media-centre/media-releases/2026/september/mr04226_singapore-external-trade-august-2026',notes:'Scheduled from Enterprise Singapore’s published standing release rule: monthly trade statistics are released on the 17th or nearest working day.'}),
    e({country:'SG',market:'Singapore',event:'Singapore External Trade / NODX',category:'trade',date:'2026-12-17',time:null,timezone:'Asia/Singapore',importance:'high',transmissionChannels:['FX','RATES','CREDIT','EQUITIES'],source:'Enterprise Singapore',sourceUrl:'https://www.enterprisesg.gov.sg/resources/media-centre/media-releases/2026/september/mr04226_singapore-external-trade-august-2026',notes:'Scheduled from Enterprise Singapore’s published standing release rule: monthly trade statistics are released on the 17th or nearest working day.'}),

    // JAPAN — Bank of Japan official 2026 Monetary Policy Meeting schedule.
    e({country:'JP',market:'Japan',event:'Bank of Japan Monetary Policy Meeting — decision day',category:'monetary-policy',date:'2026-10-30',time:null,timezone:'Asia/Tokyo',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'Bank of Japan',sourceUrl:'https://www.boj.or.jp/en/mopo/mpmsche_minu/m_ref/mref250731a.pdf'}),
    e({country:'JP',market:'Japan',event:'Bank of Japan Monetary Policy Meeting — decision day',category:'monetary-policy',date:'2026-12-18',time:null,timezone:'Asia/Tokyo',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'Bank of Japan',sourceUrl:'https://www.boj.or.jp/en/mopo/mpmsche_minu/m_ref/mref250731a.pdf'}),

    // AUSTRALIA — Reserve Bank of Australia official Board schedule.
    e({country:'AU',market:'Australia',event:'RBA Monetary Policy Decision',category:'monetary-policy',date:'2026-09-29',time:'14:30',timezone:'Australia/Sydney',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'Reserve Bank of Australia',sourceUrl:'https://www.rba.gov.au/schedules-events/board-meeting-schedules.html'}),
    e({country:'AU',market:'Australia',event:'RBA Monetary Policy Decision',category:'monetary-policy',date:'2026-11-03',time:'14:30',timezone:'Australia/Sydney',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'Reserve Bank of Australia',sourceUrl:'https://www.rba.gov.au/schedules-events/board-meeting-schedules.html'}),
    e({country:'AU',market:'Australia',event:'RBA Monetary Policy Decision',category:'monetary-policy',date:'2026-12-08',time:'14:30',timezone:'Australia/Sydney',importance:'high',transmissionChannels:['RATES','FX','SOVEREIGN_CURVE'],source:'Reserve Bank of Australia',sourceUrl:'https://www.rba.gov.au/schedules-events/board-meeting-schedules.html'})
  ];
}
